### ISSUE TITLE
goodt҈҉ͯͭͬͫͪͨ́̓ ҈҉͓̗̯̓͆͂ͫ͘firstt҈҉ͯͭͬͫͪͨ́̓ ҈҉͘ssue table secrt҈҉ͯͭͬͫͪͨ́̓ secret

### ISSUE THREAD

**Issue by ljy-002** [MapMaths/mapmaths.github.io#3]
goodt҈҉ͯͭͬͫͪͨ́̓ ҈҉͓̗̯̓͆͂ͫ͘firstt҈҉ͯͭͬͫͪͨ́̓ ҈҉͘ssue table secrt҈҉ͯͭͬͫͪͨ́̓ secret

**Comment by ljy-002** [comment]
goodt҈҉ͯͭͬͫͪͨ́̓ ҈҉͓̗̯̓͆͂ͫ͘firstt҈҉ͯͭͬͫͪͨ́̓ ҈҉͘ssue table secrt҈҉ͯͭͬͫͪͨ́̓ secret

**Comment by ljy-002** [comment]
有什么用吗？？？

**Comment by MapMaths** [comment]
That's not an issue,  I closed it~
