### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by ghost** [MapMaths/mapmaths.github.io#4]
1.你可以不用建造英文网页，主页就可以了；
2.你的中文网页没有更新哦；
3.更新日志没有中文的呀！

你可以创建一个其他语言（比如中文）文件夹，里面放中文的东西，互相调用！

谢谢

**Comment by MapMaths** [comment]
嗯嗯，谢谢

**Comment by MapMaths** [comment]
我打算用JavaScript把两个融合起来，所以暂时没有更新~
